Badges
PRABgit01/Story-craft pull request #9
Opened 2023-12-22 09:45 UTC by PRABgit01

### Badges on Avtar 
<img width="1271" alt="Screenshot 2023-12-22 at 3 14 11 PM" src="https://github.com/PRABgit01/Addons-Component/assets/153066539/e86d5068-2a0e-4a42-8f2e-36bc82f9faa2">

### Badges on icon
<img width="1275" alt="Screenshot 2023-12-22 at 3 14 22 PM" src="https://github.com/PRABgit01/Addons-Component/assets/153066539/6ad4edd9-109b-4d59-a29a-163a741d4b6d">

2023-12-27 11:55 UTC, tarakhant1297 requested changes

2023-12-27 11:55 UTC, tarakhant1297 commented on src/stories/Badges/Badge.js
> +const Badge = ({ url, type, variant, colorInput,text }) => {
@PRABgit01 file name and folder name should be same

2023-12-27 11:55 UTC, tarakhant1297 commented on src/stories/Badges/Badge.js
> +        <BadgeIcon colorInput={colorInput} type={type} />
@PRABgit01 give proper name to colorInput

2023-12-27 11:55 UTC, tarakhant1297 commented on src/stories/Badges/Badge.style.js
> +const sizes = {
@PRABgit01 move this to size.js file

2023-12-29 03:49 UTC, ankitadrixus08 commented on src/stories/Badges/Badge.styled.js
> +  border: 2px solid;
use shorthand prop @PRABgit01

2023-12-29 05:14 UTC, PRABgit01 commented on src/stories/Badges/Badge.style.js
> +  border: 2px solid;
i have done the changes

2023-12-29 05:15 UTC, PRABgit01 commented on src/stories/Badges/Badge.style.js
> +  color: white;
here i have imported the the color from the theme file

2023-12-29 05:19 UTC, ankitadrixus08 approved these changes

2023-12-29 06:10 UTC, tarakhant1297 requested changes

2023-12-29 06:10 UTC, tarakhant1297 commented on src/stories/Badges/sizes.js
> +  small: { height: 2.4, top: 59, left: 37, topIcon: 9, leftIcon: 44 },
@PRABgit01 why you add `top: 59, left: 37, topIcon: 9, leftIcon: 44`

2023-12-29 06:11 UTC, tarakhant1297 requested changes

2023-12-29 06:11 UTC, tarakhant1297 commented on src/stories/Badges/Badge.js
> +        <StyledBadgeIcon colorInput={colorInput} type={type} />
@PRABgit01 give proper name to `colorInput `

2024-01-01 06:23 UTC, tarakhant1297 approved these changes

2024-01-01 08:49 UTC, merged